apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-atlas-operator
  annotations:
    meta.crossplane.io/maintainer: Jonasz Lasut-Balcerzak <jonasz.lasut@gmail.com>
    meta.crossplane.io/source: github.com/jonasz-lasut/configuration-atlas-operator
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This Crossplane configuration is a starting point to use gitops in your own internal cloud.
    meta.crossplane.io/readme: |
      This Crossplane configuration is a starting point to use gitops in your own internal cloud.
      To learn more checkout the [GitHub repo](https:// github.com/jonasz-lasut/configuration-atlas-operator/)
      that you can copy and customize to meet the exact needs of your organization!
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      # renovate: datasource=github-releases depName=crossplane-contrib/provider-helm
      version: "v0.19.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      # renovate: datasource=github-releases depName=crossplane-contrib/provider-kubernetes
      version: "v0.14.1"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      # renovate: datasource=github-releases depName=crossplane-contrib/function-patch-and-transform
      version: "v0.7.0"
